genericSlot=function(aslot){
	if(!isGeneric(aslot)) {
		if(is.function(aslot))
		fun <- eval(aslot)
		else fun <- function(object) standardGeneric(aslot)
		setGeneric(aslot, fun)
	}
}
genericSlot("seq_num")
genericSlot("kaks")
genericSlot("lod")
genericSlot("q")
genericSlot("ka")
genericSlot("ks")
genericSlot("mi")
genericSlot("p.value")
genericSlot("ckaks")
genericSlot("method")
genericSlot("positiveSite01")
genericSlot("positiveSite02")
genericSlot("state_1")
genericSlot("statistic_1")
genericSlot("state_2")
genericSlot("statistic_2")
setMethod("seq_num","kaksAA",function(object) object@seq_num)
setMethod("kaks","kaksAA",function(object) object@kaks)
setMethod("lod","kaksAA",function(object) object@lod)
setMethod("q","kaksAA",function(object) object@q)
setMethod("ka","kaksAA",function(object) object@ka)
setMethod("ks","kaksAA",function(object) object@ks)
setMethod("seq_num","kaksCodon",function(object) object@seq_num)
setMethod("kaks","kaksCodon",function(object) object@kaks)
setMethod("lod","kaksCodon",function(object) object@lod)
setMethod("q","kaksCodon",function(object) object@q)
setMethod("ka","kaksCodon",function(object) object@ka)
setMethod("ks","kaksCodon",function(object) object@ks)
setMethod("mi","MI",function(object) object@mi)
setMethod("p.value","MI",function(object) object@p.value)
setMethod("ckaks","ckaks",function(object) object@ckaks)
setMethod("lod","ckaks",function(object) object@lod)
#
setMethod("method","biCompare",function(object) object@method)
setMethod("positiveSite01","biCompare",function(object) object@positiveSite01)
setMethod("positiveSite02","biCompare",function(object) object@positiveSite02)
setMethod("state_1","biCompare",function(object) object@state_1)
setMethod("statistic_1","biCompare",function(object) object@statistic_1)
setMethod("state_2","biCompare",function(object) object@state_2)
setMethod("statistic_2","biCompare",function(object) object@statistic_2)
