genericSlot=function(aslot){
	if(!isGeneric(aslot)) {
		if(is.function(aslot))
		fun <- eval(aslot)
		else fun <- function(object) standardGeneric(aslot)
		setGeneric(aslot, fun)
	}
}
genericSlot("seq_num.CorMut")
genericSlot("kaks.CorMut")
genericSlot("lod.CorMut")
genericSlot("q.CorMut")
genericSlot("ka.CorMut")
genericSlot("ks.CorMut")
genericSlot("mi.CorMut")
genericSlot("p.value.CorMut")
genericSlot("ckaks.CorMut")
genericSlot("method.CorMut")
genericSlot("positiveSite01.CorMut")
genericSlot("positiveSite02.CorMut")
genericSlot("state_1.CorMut")
genericSlot("statistic_1.CorMut")
genericSlot("state_2.CorMut")
genericSlot("statistic_2.CorMut")
setMethod("seq_num.CorMut","kaksAA",function(object) object@seq_num)
setMethod("kaks.CorMut","kaksAA",function(object) object@kaks)
setMethod("lod.CorMut","kaksAA",function(object) object@lod)
setMethod("q.CorMut","kaksAA",function(object) object@q)
setMethod("ka.CorMut","kaksAA",function(object) object@ka)
setMethod("ks.CorMut","kaksAA",function(object) object@ks)
setMethod("seq_num.CorMut","kaksCodon",function(object) object@seq_num)
setMethod("kaks.CorMut","kaksCodon",function(object) object@kaks)
setMethod("lod.CorMut","kaksCodon",function(object) object@lod)
setMethod("q.CorMut","kaksCodon",function(object) object@q)
setMethod("ka.CorMut","kaksCodon",function(object) object@ka)
setMethod("ks.CorMut","kaksCodon",function(object) object@ks)
setMethod("mi.CorMut","MI",function(object) object@mi)
setMethod("p.value.CorMut","MI",function(object) object@p.value)
setMethod("ckaks.CorMut","ckaks",function(object) object@ckaks)
setMethod("lod.CorMut","ckaks",function(object) object@lod)
#
setMethod("method.CorMut","biCompare",function(object) object@method)
setMethod("positiveSite01.CorMut","biCompare",function(object) object@positiveSite01)
setMethod("positiveSite02.CorMut","biCompare",function(object) object@positiveSite02)
setMethod("state_1.CorMut","biCompare",function(object) object@state_1)
setMethod("statistic_1.CorMut","biCompare",function(object) object@statistic_1)
setMethod("state_2.CorMut","biCompare",function(object) object@state_2)
setMethod("statistic_2.CorMut","biCompare",function(object) object@statistic_2)
